### ISSUE TITLE
Github makes me stupid

### ISSUE THREAD

**Issue by emailing-files-is-still-better** [georgev93/IR_blinker#1]
It's probably staring me in the face somewhere.......but I do not see a .zip file anywhere.......Halp!

**Comment by georgev93** [comment]
![Screenshot_20221211-212506_Chrome.jpg](https://user-images.githubusercontent.com/39860568/206909419-d1cbf1f0-2e06-41c7-944b-fba8bf3f5eae.jpg)

On the right side, under releases

![Screenshot_20221211-212555_Chrome.jpg](https://user-images.githubusercontent.com/39860568/206909443-580bbd3f-6412-4489-b3cf-6c3445bfb2aa.jpg)

**Comment by emailing-files-is-still-better** [comment]
Ok i'll be honest, I don't feel so bad about not finding that haha. Why isn't it front and center like all of the other files!
