### ISSUE TITLE
Setting the current for the IR LED

### ISSUE THREAD

**Issue by georgev93** [georgev93/IR_blinker#2]
So @emailing-files-is-still-better, not knowing what IR LED you're using for this bad boy I wasn't able to exactly dial in the current we want. Therefore, R1 is at 150 Ohms, which works well for a surface mount LED I picked out before I switched it to an off-board IR LED. Once you know your IR LED, you'll want to set the current appropriately (although 150 ohms might do you just fine).

### Step 1: Pick luminosity

If you have the datasheet, there should be a graph that correlates current to luminosity (or radiant intensity, lux, brightness, etc.). Like this one for the [TSAL6100](https://components101.com/sites/default/files/component_datasheet/IR%20LED%20datasheet.pdf): 

![radiant_intensity](https://user-images.githubusercontent.com/39860568/210302078-c3cb5d34-35e6-4ea0-917a-186045dec3d8.png)

(Note the nearly linear relationship between log(current) and log(radiant intensity))

Pick your value. Better yet, if you have a lab power supply, drive a constant current through the LED, then pick your favorite luminosity. You can set a power supply in "constant current" mode by setting your limit to something like 10mA, then set your voltage to something that is higher than what you expect the forward voltage drop to be (like 5V). When you connect the LED to the power supply, it will only let 10mA through, so it will drop the voltage until it achieves that current (constant current mode).

 One way or another, this value determines the current that we want to run through the LED. You can likely use your phone camera to compare brightness of LEDs (although if you're comparing to a 50% duty cycle LED, it'll show up half as bright!)

### Step 2: Determine Your Current

Use either the graph from the datasheet or your experimental results to choose the current you want to drive your LED at.

### Step 3: Determine the Forward Voltage of that LED at the Given Current

The LED will drop a certain voltage across it based on the current you push through. If you have the datasheet on hand, there should be a graph with this information. Like this one:

![forward_voltage](https://user-images.githubusercontent.com/39860568/210302426-8c2b425a-e29d-4674-9819-700dd9496321.png)

(Note the higher the current, the higher the forward voltage drop)

If you don't have the datasheet on hand, look at the power supply when you're pushing your chosen current through. The power supply will be making a voltage equal to the forward voltage drop of the LED.

### Step 4: Determine the value of R1

Finally! What we came here to do. The R1/LED combo is being supplied with a regulated 3.3V. Subtract out the forward voltage drop of the LED from 3.3V, and you'll be left with the voltage drop across the resistor. Then use Ohm's Law (`V = I * R`) to find the value of your resistor.

Example: You want your current to be 10mA, which means the LED has a forward voltage drop of 1.2V. You have 2.1V to drop over R1 (`3.3V - 1.2V = 2.1V`). Your resistor that you need is 210 Ohms (`2.1V = 0.010A * R`, `R = 2.1V / 0.010A = 210 Ohms`).

I know a place where you could steal an 0603 resistor or two...

**Comment by georgev93** [comment]
Alternatively, you could always wing it with 150 ohms for R1. Just know that could be kind of a pain in the ass to unsolder that 0603 resistor and replace it with something else when the rest of the board is already populated

**Comment by georgev93** [comment]
And try to keep the current under 100 mA if you can. Much higher and we risk overheating the regulator

**Comment by emailing-files-is-still-better** [comment]
![Screenshot_20230103-142737_Lazada.jpg](https://user-images.githubusercontent.com/120235689/210315046-c4dfc852-cebb-467e-9259-7e34920306ad.jpg)

So this is what I currently have on hand, and as close to a data sheet as possible haha. Winging it was my plan for the first board, I mean how much can LEDs really vary 😉

**Comment by georgev93** [comment]
From the small amount of English in that, there's a few specs that would indicate that we're looking at an LED, but it also says "receiver" a few times. Is this an LED or a photodiode?

**Comment by emailing-files-is-still-better** [comment]
Haha. Both are sold from the same page, wasn't sure if there was led data mixed in there as well. https://s.lazada.co.th/s.iLXsA

**Comment by georgev93** [comment]
If that's describing the LED as having a forward voltage of 1.1-1.4V, then a 150 ohm R1 would set the current somewhere between 12.7-14.7mA. That's likely a very comfortable point to operate at given that it seems to list the max current as 30mA. Just know that you can nearly double the brightness if you need to by decreasing R1.

**Comment by emailing-files-is-still-better** [comment]
Well that gives me enough confidence to at least try one, brightness would just increase range right? Or would it also increase reliability at high passing speeds?

**Comment by georgev93** [comment]
Correct; I think brightness could increase your range. Too dim might also result in poor reliability
